title: My new Jekyll site
email: your-email@domain.com
description: This is my awesome site powered by Jekyll!
baseurl: "/jekyll"
url: LazsloBunz.github.io
twitter_username: jekyllrb
github_username: LazsloBunz
markdown: kramdown
theme: clean-jekyll
